# Generated by Django 5.2.7 on 2025-11-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bid_placed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='placed_at',
            new_name='placed_on',
        ),
    ]
